name             'grafana'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Installs/Configures Grafana Server'
source_url       'https://github.com/willholley/grafana'
issues_url       'https://github.com/willholley/grafana/issues'
chef_version     '>= 16.0'
version          '10.6.5'

supports 'debian'
supports 'ubuntu'
supports 'redhat'
supports 'centos'
supports 'fedora'
supports 'amazon'
supports 'scientific'
supports 'oracle'

depends 'build-essential'

gem 'deepsort'
gem 'inifile'
